import mockDataObject from './mockData.json'

  // let businessArray = [mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject, mockDataObject];
const businessesArray = [
    {...mockDataObject,
        "name": "Kasias Baps",
        "city": "London",
        "zipCode": "EC2A2DF",
        "category": "Chinese Baps",
        "rating": 5,
        "review_count": 69    
    }, 
    {...mockDataObject,
        "name": "Tarths Brazzo Grill",
        "city": "Kings Thorpe",
        "zipCode": "EC2A2DF",
        "category": "Brazzo",
        "rating": 4.1,
        "review_count": 111    
    }, 
    {...mockDataObject,
        "name": "Dantes Infernos",
        "city": "New York",
        "zipCode": "100011",
        "category": "Rizz",
        "rating": 4.0,
        "review_count": 99    
    }, 
    {...mockDataObject,
      "name": "Grottos Pizzeria",
      "city": "Lil VIllage",
      "zipCode": "10001",
      "category": "Italian",
      "rating": 4.0,
      "review_count": 9000    
    }, 
    {...mockDataObject,
      "name": "Dominos",
      "city": "Cloud",
      "zipCode": "456289",
      "category": "Dirty Italian",
      "rating": 4.6,
      "review_count": 900000    
    }, 
    {...mockDataObject,
      "name": "BussLand",
      "city": "BGreen",
      "zipCode": "10001",
      "category": "Shit",
      "rating": 3.1,
      "review_count": 956    
    }, 
    {...mockDataObject,
        "name": "The Golden Dragon",
        "city": "San Francisco",
        "zipCode": "94102",
        "category": "Chinese",
        "rating": 4.5,
        "review_count": 234    
    }, 
    {...mockDataObject,
        "name": "Bella Vista Ristorante",
        "city": "Chicago",
        "zipCode": "60614",
        "category": "Italian",
        "rating": 4.3,
        "review_count": 189    
    }, 
    {...mockDataObject,
        "name": "Sakura Sushi Bar",
        "city": "Seattle",
        "zipCode": "98101",
        "category": "Japanese",
        "rating": 4.7,
        "review_count": 312    
    }, 
    {...mockDataObject,
      "name": "El Mariachi Cantina",
      "city": "Austin",
      "zipCode": "78701",
      "category": "Mexican",
      "rating": 4.2,
      "review_count": 156    
    }, 
    {...mockDataObject,
      "name": "The French Quarter",
      "city": "New Orleans",
      "zipCode": "70116",
      "category": "French",
      "rating": 4.6,
      "review_count": 278    
    }, 
    {...mockDataObject,
      "name": "Spice Garden",
      "city": "Miami",
      "zipCode": "33101",
      "category": "Indian",
      "rating": 4.4,
      "review_count": 203    
    }, 
    {...mockDataObject,
      "name": "Ocean Breeze Cafe",
      "city": "Portland",
      "zipCode": "97201",
      "category": "Seafood",
      "rating": 4.1,
      "review_count": 167    
    }, 
    
    {...mockDataObject,
        "name": "Mountain View Diner",
        "city": "Denver",
        "zipCode": "80202",
        "category": "American",
        "rating": 4.0,
        "review_count": 145    
    }, 
    {...mockDataObject,
        "name": "Cafe de Paris",
        "city": "Boston",
        "zipCode": "02108",
        "category": "French",
        "rating": 4.5,
        "review_count": 198    
    }, 
    {...mockDataObject,
        "name": "Tokyo Ramen House",
        "city": "Los Angeles",
        "zipCode": "90012",
        "category": "Japanese",
        "rating": 4.3,
        "review_count": 267    
    }, 
    {...mockDataObject,
      "name": "Mediterranean Breeze",
      "city": "Phoenix",
      "zipCode": "85001",
      "category": "Mediterranean",
      "rating": 4.2,
      "review_count": 134    
    }, 
    {...mockDataObject,
      "name": "BBQ Smokehouse",
      "city": "Kansas City",
      "zipCode": "64106",
      "category": "BBQ",
      "rating": 4.8,
      "review_count": 423    
    }, 
    {...mockDataObject,
      "name": "Veggie Delight",
      "city": "Portland",
      "zipCode": "97205",
      "category": "Vegetarian",
      "rating": 4.4,
      "review_count": 189    
    }, 
    {...mockDataObject,
      "name": "The Steakhouse",
      "city": "Dallas",
      "zipCode": "75201",
      "category": "Steakhouse",
      "rating": 4.6,
      "review_count": 356    
    }
]

export default businessesArray;
